#! /bin/sh

set -e

BASE="`dirname "$0"`"
if [ ! -e "$BASE/settings.gradle" ]; then
    echo "$BASE/settings.gradle does not exist" 1>&2
    exit 1
fi
NAME="`grep rootProject.name "$BASE/settings.gradle" | sed -e"s/^.*= *'\(.*\)'$/\1/g"`"

PROJECTDIR="`pwd`"

IMAGE="`docker stop "build-$NAME-$USER"`" >/dev/null 2>&1 || true
IMAGE="`docker rm "build-$NAME-$USER"`" >/dev/null 2>&1 || true
while [ "$(docker inspect -f '{{.State.Running}}' "build-$NAME-$USER" 2>/dev/null)" = "true" ]; do
    sleep 1
done
install -d "$HOME/.build-home/project"

OPTS=
if tty -s; then
    OPTS="$OPTS -t"
fi
if [ ! -z "$SSH_AUTH_SOCK" -a -e "$SSH_AUTH_SOCK" ]; then
    OPTS="$OPTS --volume=$SSH_AUTH_SOCK:/ssh-agent"
fi

docker run \
    --name="build-$NAME-$USER" \
    $OPTS \
    -i \
    --rm \
    --volume="$HOME/.build-home:/home/user" \
    --volume="$PROJECTDIR:/home/user/project" \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    "build-$NAME-$USER" "$@"
