/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_root (void)
{
  GtkWidget *window_root;
  GtkWidget *vbox2;
  GtkWidget *hbox6;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *quit_character1;
  GtkWidget *quit2;
  GtkWidget *client1;
  GtkWidget *client1_menu;
  GtkWidget *configure1;
  GtkWidget *disconnect;
  GtkWidget *keybindings;
  GtkWidget *save_window_position;
  GtkWidget *menu_player;
  GtkWidget *menu_player_menu;
  GtkWidget *spells;
  GtkWidget *pickup1;
  GtkWidget *pickup1_menu;
  GtkWidget *don_t_pickup1;
  GtkWidget *stop_before_pickup1;
  GtkWidget *armor1;
  GtkWidget *armor1_menu;
  GtkWidget *body_armor1;
  GtkWidget *boots1;
  GtkWidget *cloaks1;
  GtkWidget *gloves1;
  GtkWidget *helmets1;
  GtkWidget *shields1;
  GtkWidget *books1;
  GtkWidget *books1_menu;
  GtkWidget *skillscrolls1;
  GtkWidget *normal_book_scrolls1;
  GtkWidget *spellbooks1;
  GtkWidget *drinks1;
  GtkWidget *food1;
  GtkWidget *keys1;
  GtkWidget *magical_items;
  GtkWidget *potions;
  GtkWidget *valuables;
  GtkWidget *wands_rods_horns;
  GtkWidget *weapons1;
  GtkWidget *weapons1_menu;
  GtkWidget *all_weapons;
  GtkWidget *missile_weapons1;
  GtkWidget *bows1;
  GtkWidget *arrows1;
  GtkWidget *weight_value_1;
  GtkWidget *weight_value_1_menu;
  GSList *ratio_pickup_off1_group = NULL;
  GtkWidget *ratio_pickup_off1;
  GtkWidget *ratio_5;
  GtkWidget *ratio_10;
  GtkWidget *ratio_15;
  GtkWidget *ratio_20;
  GtkWidget *ratio_25;
  GtkWidget *ratio_30;
  GtkWidget *ratio_35;
  GtkWidget *ratio_40;
  GtkWidget *ratio_45;
  GtkWidget *ratio_50;
  GtkWidget *not_cursed1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about1;
  GtkWidget *fire_on;
  GtkWidget *run_on;
  GtkWidget *filler;
  GtkWidget *hpaned_map_other;
  GtkWidget *vpaned_map_stats;
  GtkWidget *map_notebook;
  GtkWidget *table_map;
  GtkWidget *drawingarea_map;
  GtkWidget *button_map_recenter;
  GtkWidget *vscrollbar_map;
  GtkWidget *hscrollbar_map;
  GtkWidget *label46;
  GtkWidget *drawingarea_magic_map;
  GtkWidget *label47;
  GtkWidget *hpaned_statbar_stats;
  GtkWidget *table4;
  GtkWidget *label_stats_hp;
  GtkWidget *label_stats_sp;
  GtkWidget *label_stats_grace;
  GtkWidget *label_stats_food;
  GtkWidget *progressbar_hp;
  GtkWidget *progressbar_sp;
  GtkWidget *progressbar_grace;
  GtkWidget *progressbar_food;
  GtkWidget *fire_label;
  GtkWidget *run_label;
  GtkWidget *label_stats_exp;
  GtkWidget *progressbar_exp;
  GtkWidget *notebook3;
  GtkWidget *vbox6;
  GtkWidget *label_playername;
  GtkWidget *hbox8;
  GtkWidget *label49;
  GtkWidget *label_str;
  GtkWidget *label51;
  GtkWidget *label_dex;
  GtkWidget *label53;
  GtkWidget *label_con;
  GtkWidget *label55;
  GtkWidget *label_int;
  GtkWidget *label57;
  GtkWidget *label_wis;
  GtkWidget *label59;
  GtkWidget *label_pow;
  GtkWidget *label61;
  GtkWidget *label_cha;
  GtkWidget *hbox4;
  GtkWidget *label32;
  GtkWidget *label_wc;
  GtkWidget *label34;
  GtkWidget *label_dam;
  GtkWidget *label36;
  GtkWidget *label_ac;
  GtkWidget *label38;
  GtkWidget *label_armor;
  GtkWidget *hbox9;
  GtkWidget *label64;
  GtkWidget *label_speed;
  GtkWidget *label66;
  GtkWidget *label_weapon_speed;
  GtkWidget *label_range;
  GtkWidget *hbox7;
  GtkWidget *label_exp;
  GtkWidget *label_level;
  GtkWidget *label14;
  GtkWidget *table_skills_exp;
  GtkWidget *label15;
  GtkWidget *table_protections;
  GtkWidget *label16;
  GtkWidget *vpaned_info_inventory;
  GtkWidget *vbox_info_entry;
  GtkWidget *notebook_info;
  GtkWidget *scrolledwindow_textview1;
  GtkWidget *textview_info1;
  GtkWidget *label1;
  GtkWidget *scrolledwindow_textview2;
  GtkWidget *textview_info2;
  GtkWidget *label2;
  GtkWidget *entry_commands;
  GtkWidget *vpaned_inv_look;
  GtkWidget *vbox3;
  GtkWidget *hbox1;
  GtkWidget *label3;
  GtkWidget *label_inv_weight;
  GtkWidget *label5;
  GtkObject *spinbutton_count_adj;
  GtkWidget *spinbutton_count;
  GtkWidget *notebook_inv;
  GtkWidget *scrolledwindow6;
  GtkWidget *viewport1;
  GtkWidget *inv_table;
  GtkWidget *label80;
  GtkWidget *vbox4;
  GtkWidget *label9;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview_look;

  window_root = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_root), _("Crossfire Client - GTK v2"));
  gtk_window_set_default_size (GTK_WINDOW (window_root), 1201, 1010);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (window_root), vbox2);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox6, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (hbox6), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  quit_character1 = gtk_menu_item_new_with_mnemonic (_("Quit Character"));
  gtk_widget_show (quit_character1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit_character1);

  quit2 = gtk_menu_item_new_with_mnemonic (_("_Quit"));
  gtk_widget_show (quit2);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit2);

  client1 = gtk_menu_item_new_with_mnemonic (_("_Client"));
  gtk_widget_show (client1);
  gtk_container_add (GTK_CONTAINER (menubar1), client1);

  client1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (client1), client1_menu);

  configure1 = gtk_menu_item_new_with_mnemonic (_("Configure"));
  gtk_widget_show (configure1);
  gtk_container_add (GTK_CONTAINER (client1_menu), configure1);

  disconnect = gtk_menu_item_new_with_mnemonic (_("Disconnect"));
  gtk_widget_show (disconnect);
  gtk_container_add (GTK_CONTAINER (client1_menu), disconnect);

  keybindings = gtk_menu_item_new_with_mnemonic (_("Keybindings"));
  gtk_widget_show (keybindings);
  gtk_container_add (GTK_CONTAINER (client1_menu), keybindings);

  save_window_position = gtk_menu_item_new_with_mnemonic (_("Save Window Position"));
  gtk_widget_show (save_window_position);
  gtk_container_add (GTK_CONTAINER (client1_menu), save_window_position);

  menu_player = gtk_menu_item_new_with_mnemonic (_("Player"));
  gtk_widget_show (menu_player);
  gtk_container_add (GTK_CONTAINER (menubar1), menu_player);

  menu_player_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menu_player), menu_player_menu);

  spells = gtk_menu_item_new_with_mnemonic (_("Spells"));
  gtk_widget_show (spells);
  gtk_container_add (GTK_CONTAINER (menu_player_menu), spells);

  pickup1 = gtk_menu_item_new_with_mnemonic (_("Pickup"));
  gtk_widget_show (pickup1);
  gtk_container_add (GTK_CONTAINER (menubar1), pickup1);

  pickup1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (pickup1), pickup1_menu);

  don_t_pickup1 = gtk_check_menu_item_new_with_mnemonic (_("Don't Pickup"));
  gtk_widget_show (don_t_pickup1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), don_t_pickup1);

  stop_before_pickup1 = gtk_check_menu_item_new_with_mnemonic (_("Stop Before Pickup"));
  gtk_widget_show (stop_before_pickup1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), stop_before_pickup1);

  armor1 = gtk_menu_item_new_with_mnemonic (_("Armor"));
  gtk_widget_show (armor1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), armor1);

  armor1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (armor1), armor1_menu);

  body_armor1 = gtk_check_menu_item_new_with_mnemonic (_("Body Armor"));
  gtk_widget_show (body_armor1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), body_armor1);

  boots1 = gtk_check_menu_item_new_with_mnemonic (_("Boots"));
  gtk_widget_show (boots1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), boots1);

  cloaks1 = gtk_check_menu_item_new_with_mnemonic (_("Cloaks"));
  gtk_widget_show (cloaks1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), cloaks1);

  gloves1 = gtk_check_menu_item_new_with_mnemonic (_("Gloves"));
  gtk_widget_show (gloves1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), gloves1);

  helmets1 = gtk_check_menu_item_new_with_mnemonic (_("Helmets"));
  gtk_widget_show (helmets1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), helmets1);

  shields1 = gtk_check_menu_item_new_with_mnemonic (_("Shields"));
  gtk_widget_show (shields1);
  gtk_container_add (GTK_CONTAINER (armor1_menu), shields1);

  books1 = gtk_menu_item_new_with_mnemonic (_("Books"));
  gtk_widget_show (books1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), books1);

  books1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (books1), books1_menu);

  skillscrolls1 = gtk_check_menu_item_new_with_mnemonic (_("Skillscrolls"));
  gtk_widget_show (skillscrolls1);
  gtk_container_add (GTK_CONTAINER (books1_menu), skillscrolls1);

  normal_book_scrolls1 = gtk_check_menu_item_new_with_mnemonic (_("Normal Books & Scrolls"));
  gtk_widget_show (normal_book_scrolls1);
  gtk_container_add (GTK_CONTAINER (books1_menu), normal_book_scrolls1);

  spellbooks1 = gtk_check_menu_item_new_with_mnemonic (_("Spellbooks"));
  gtk_widget_show (spellbooks1);
  gtk_container_add (GTK_CONTAINER (books1_menu), spellbooks1);

  drinks1 = gtk_check_menu_item_new_with_mnemonic (_("Drinks"));
  gtk_widget_show (drinks1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), drinks1);

  food1 = gtk_check_menu_item_new_with_mnemonic (_("Food"));
  gtk_widget_show (food1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), food1);

  keys1 = gtk_check_menu_item_new_with_mnemonic (_("Keys"));
  gtk_widget_show (keys1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), keys1);

  magical_items = gtk_check_menu_item_new_with_mnemonic (_("Magical Items"));
  gtk_widget_show (magical_items);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), magical_items);

  potions = gtk_check_menu_item_new_with_mnemonic (_("Potions"));
  gtk_widget_show (potions);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), potions);

  valuables = gtk_check_menu_item_new_with_mnemonic (_("Valuables (Money & Gems)"));
  gtk_widget_show (valuables);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), valuables);

  wands_rods_horns = gtk_check_menu_item_new_with_mnemonic (_("Wands/Rods/Horns"));
  gtk_widget_show (wands_rods_horns);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), wands_rods_horns);

  weapons1 = gtk_menu_item_new_with_mnemonic (_("Weapons"));
  gtk_widget_show (weapons1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), weapons1);

  weapons1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (weapons1), weapons1_menu);

  all_weapons = gtk_check_menu_item_new_with_mnemonic (_("All Weapons"));
  gtk_widget_show (all_weapons);
  gtk_container_add (GTK_CONTAINER (weapons1_menu), all_weapons);

  missile_weapons1 = gtk_check_menu_item_new_with_mnemonic (_("Missile Weapons"));
  gtk_widget_show (missile_weapons1);
  gtk_container_add (GTK_CONTAINER (weapons1_menu), missile_weapons1);

  bows1 = gtk_check_menu_item_new_with_mnemonic (_("Bows"));
  gtk_widget_show (bows1);
  gtk_container_add (GTK_CONTAINER (weapons1_menu), bows1);

  arrows1 = gtk_check_menu_item_new_with_mnemonic (_("Arrows"));
  gtk_widget_show (arrows1);
  gtk_container_add (GTK_CONTAINER (weapons1_menu), arrows1);

  weight_value_1 = gtk_menu_item_new_with_mnemonic (_("Weight/Value "));
  gtk_widget_show (weight_value_1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), weight_value_1);

  weight_value_1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (weight_value_1), weight_value_1_menu);

  ratio_pickup_off1 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio Pickup Off"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_pickup_off1));
  gtk_widget_show (ratio_pickup_off1);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_pickup_off1);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_pickup_off1), TRUE);

  ratio_5 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 5"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_5));
  gtk_widget_show (ratio_5);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_5);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_5), TRUE);

  ratio_10 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 10"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_10));
  gtk_widget_show (ratio_10);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_10);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_10), TRUE);

  ratio_15 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 15"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_15));
  gtk_widget_show (ratio_15);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_15);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_15), TRUE);

  ratio_20 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 20"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_20));
  gtk_widget_show (ratio_20);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_20);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_20), TRUE);

  ratio_25 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 25"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_25));
  gtk_widget_show (ratio_25);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_25);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_25), TRUE);

  ratio_30 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 30"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_30));
  gtk_widget_show (ratio_30);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_30);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_30), TRUE);

  ratio_35 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 35"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_35));
  gtk_widget_show (ratio_35);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_35);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_35), TRUE);

  ratio_40 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 40"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_40));
  gtk_widget_show (ratio_40);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_40);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_40), TRUE);

  ratio_45 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 45"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_45));
  gtk_widget_show (ratio_45);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_45);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_45), TRUE);

  ratio_50 = gtk_radio_menu_item_new_with_mnemonic (ratio_pickup_off1_group, _("Ratio >= 50"));
  ratio_pickup_off1_group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (ratio_50));
  gtk_widget_show (ratio_50);
  gtk_container_add (GTK_CONTAINER (weight_value_1_menu), ratio_50);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (ratio_50), TRUE);

  not_cursed1 = gtk_check_menu_item_new_with_mnemonic (_("Ignore cursed"));
  gtk_widget_show (not_cursed1);
  gtk_container_add (GTK_CONTAINER (pickup1_menu), not_cursed1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about1);

  fire_on = gtk_label_new ("");
  gtk_widget_show (fire_on);
  gtk_box_pack_start (GTK_BOX (hbox6), fire_on, TRUE, FALSE, 0);

  run_on = gtk_label_new ("");
  gtk_widget_show (run_on);
  gtk_box_pack_start (GTK_BOX (hbox6), run_on, FALSE, TRUE, 0);

  filler = gtk_label_new ("");
  gtk_widget_show (filler);
  gtk_box_pack_start (GTK_BOX (hbox6), filler, FALSE, FALSE, 0);

  hpaned_map_other = gtk_hpaned_new ();
  gtk_widget_show (hpaned_map_other);
  gtk_box_pack_start (GTK_BOX (vbox2), hpaned_map_other, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned_map_other), 820);

  vpaned_map_stats = gtk_vpaned_new ();
  gtk_widget_show (vpaned_map_stats);
  gtk_paned_pack1 (GTK_PANED (hpaned_map_other), vpaned_map_stats, FALSE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned_map_stats), 847);

  map_notebook = gtk_notebook_new ();
  gtk_widget_show (map_notebook);
  gtk_paned_pack1 (GTK_PANED (vpaned_map_stats), map_notebook, FALSE, TRUE);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (map_notebook), FALSE);

  table_map = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table_map);
  gtk_container_add (GTK_CONTAINER (map_notebook), table_map);

  drawingarea_map = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea_map);
  gtk_table_attach (GTK_TABLE (table_map), drawingarea_map, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_size_request (drawingarea_map, 800, 800);

  button_map_recenter = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button_map_recenter);
  gtk_table_attach (GTK_TABLE (table_map), button_map_recenter, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  vscrollbar_map = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (50, 0, 100, 0, 0, 0)));
  gtk_widget_show (vscrollbar_map);
  gtk_table_attach (GTK_TABLE (table_map), vscrollbar_map, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hscrollbar_map = gtk_hscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (50, 0, 100, 1, 0, 0)));
  gtk_widget_show (hscrollbar_map);
  gtk_table_attach (GTK_TABLE (table_map), hscrollbar_map, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label46 = gtk_label_new (_("Map"));
  gtk_widget_show (label46);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (map_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (map_notebook), 0), label46);

  drawingarea_magic_map = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea_magic_map);
  gtk_container_add (GTK_CONTAINER (map_notebook), drawingarea_magic_map);

  label47 = gtk_label_new (_("Magic Map"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (map_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (map_notebook), 1), label47);

  hpaned_statbar_stats = gtk_hpaned_new ();
  gtk_widget_show (hpaned_statbar_stats);
  gtk_paned_pack2 (GTK_PANED (vpaned_map_stats), hpaned_statbar_stats, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (hpaned_statbar_stats), 306);

  table4 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table4);
  gtk_paned_pack1 (GTK_PANED (hpaned_statbar_stats), table4, TRUE, TRUE);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 4);

  label_stats_hp = gtk_label_new (_("HP: 0/0"));
  gtk_widget_show (label_stats_hp);
  gtk_table_attach (GTK_TABLE (table4), label_stats_hp, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK),
                    (GtkAttachOptions) (0), 0, 0);

  label_stats_sp = gtk_label_new (_("Spell Points: 0/0"));
  gtk_widget_show (label_stats_sp);
  gtk_table_attach (GTK_TABLE (table4), label_stats_sp, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK),
                    (GtkAttachOptions) (0), 0, 0);

  label_stats_grace = gtk_label_new (_("Grace: 0/0"));
  gtk_widget_show (label_stats_grace);
  gtk_table_attach (GTK_TABLE (table4), label_stats_grace, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK),
                    (GtkAttachOptions) (0), 0, 0);

  label_stats_food = gtk_label_new (_("Food: 0/0"));
  gtk_widget_show (label_stats_food);
  gtk_table_attach (GTK_TABLE (table4), label_stats_food, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK),
                    (GtkAttachOptions) (0), 0, 0);

  progressbar_hp = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_hp);
  gtk_table_attach (GTK_TABLE (table4), progressbar_hp, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  progressbar_sp = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_sp);
  gtk_table_attach (GTK_TABLE (table4), progressbar_sp, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  progressbar_grace = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_grace);
  gtk_table_attach (GTK_TABLE (table4), progressbar_grace, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  progressbar_food = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_food);
  gtk_table_attach (GTK_TABLE (table4), progressbar_food, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  fire_label = gtk_label_new ("");
  gtk_widget_show (fire_label);
  gtk_table_attach (GTK_TABLE (table4), fire_label, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (fire_label), 0, 0.5);

  run_label = gtk_label_new ("");
  gtk_widget_show (run_label);
  gtk_table_attach (GTK_TABLE (table4), run_label, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (run_label), 0, 0.5);

  label_stats_exp = gtk_label_new (_("Exp: 0/0"));
  gtk_widget_show (label_stats_exp);
  gtk_table_attach (GTK_TABLE (table4), label_stats_exp, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_stats_exp), 0, 0.5);

  progressbar_exp = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_exp);
  gtk_table_attach (GTK_TABLE (table4), progressbar_exp, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_paned_pack2 (GTK_PANED (hpaned_statbar_stats), notebook3, TRUE, TRUE);

  vbox6 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox6);

  label_playername = gtk_label_new (_("Player:"));
  gtk_widget_show (label_playername);
  gtk_box_pack_start (GTK_BOX (vbox6), label_playername, FALSE, FALSE, 0);

  hbox8 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox8, TRUE, TRUE, 0);

  label49 = gtk_label_new (_("Str"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox8), label49, FALSE, FALSE, 0);

  label_str = gtk_label_new ("");
  gtk_widget_show (label_str);
  gtk_box_pack_start (GTK_BOX (hbox8), label_str, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("Dex"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox8), label51, FALSE, FALSE, 0);

  label_dex = gtk_label_new ("");
  gtk_widget_show (label_dex);
  gtk_box_pack_start (GTK_BOX (hbox8), label_dex, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("Con"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox8), label53, FALSE, FALSE, 0);

  label_con = gtk_label_new ("");
  gtk_widget_show (label_con);
  gtk_box_pack_start (GTK_BOX (hbox8), label_con, FALSE, FALSE, 0);

  label55 = gtk_label_new (_("Int"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox8), label55, FALSE, FALSE, 0);

  label_int = gtk_label_new ("");
  gtk_widget_show (label_int);
  gtk_box_pack_start (GTK_BOX (hbox8), label_int, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("Wis"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox8), label57, FALSE, FALSE, 0);

  label_wis = gtk_label_new ("");
  gtk_widget_show (label_wis);
  gtk_box_pack_start (GTK_BOX (hbox8), label_wis, FALSE, FALSE, 0);

  label59 = gtk_label_new (_("Pow"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox8), label59, FALSE, FALSE, 0);

  label_pow = gtk_label_new ("");
  gtk_widget_show (label_pow);
  gtk_box_pack_start (GTK_BOX (hbox8), label_pow, FALSE, FALSE, 0);

  label61 = gtk_label_new (_("Cha"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox8), label61, FALSE, FALSE, 0);

  label_cha = gtk_label_new ("");
  gtk_widget_show (label_cha);
  gtk_box_pack_start (GTK_BOX (hbox8), label_cha, FALSE, FALSE, 0);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox4, TRUE, TRUE, 0);

  label32 = gtk_label_new (_("WC"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox4), label32, FALSE, FALSE, 0);

  label_wc = gtk_label_new ("");
  gtk_widget_show (label_wc);
  gtk_box_pack_start (GTK_BOX (hbox4), label_wc, FALSE, FALSE, 0);

  label34 = gtk_label_new (_("Dam"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox4), label34, FALSE, FALSE, 0);

  label_dam = gtk_label_new ("");
  gtk_widget_show (label_dam);
  gtk_box_pack_start (GTK_BOX (hbox4), label_dam, FALSE, FALSE, 0);

  label36 = gtk_label_new (_("AC"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox4), label36, FALSE, FALSE, 0);

  label_ac = gtk_label_new ("");
  gtk_widget_show (label_ac);
  gtk_box_pack_start (GTK_BOX (hbox4), label_ac, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("Armor"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox4), label38, FALSE, FALSE, 0);

  label_armor = gtk_label_new ("");
  gtk_widget_show (label_armor);
  gtk_box_pack_start (GTK_BOX (hbox4), label_armor, FALSE, FALSE, 0);

  hbox9 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox9, FALSE, FALSE, 0);

  label64 = gtk_label_new (_("Speed"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox9), label64, FALSE, FALSE, 0);

  label_speed = gtk_label_new ("");
  gtk_widget_show (label_speed);
  gtk_box_pack_start (GTK_BOX (hbox9), label_speed, FALSE, FALSE, 0);

  label66 = gtk_label_new (_("Weapon Speed"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox9), label66, FALSE, FALSE, 0);

  label_weapon_speed = gtk_label_new ("");
  gtk_widget_show (label_weapon_speed);
  gtk_box_pack_start (GTK_BOX (hbox9), label_weapon_speed, FALSE, FALSE, 0);

  label_range = gtk_label_new (_("Range:"));
  gtk_widget_show (label_range);
  gtk_box_pack_start (GTK_BOX (vbox6), label_range, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox7, TRUE, TRUE, 0);

  label_exp = gtk_label_new (_("Experience:"));
  gtk_widget_show (label_exp);
  gtk_box_pack_start (GTK_BOX (hbox7), label_exp, FALSE, FALSE, 0);

  label_level = gtk_label_new (_("Level:"));
  gtk_widget_show (label_level);
  gtk_box_pack_start (GTK_BOX (hbox7), label_level, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Core Stats"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label14);

  table_skills_exp = gtk_table_new (6, 6, TRUE);
  gtk_widget_show (table_skills_exp);
  gtk_container_add (GTK_CONTAINER (notebook3), table_skills_exp);

  label15 = gtk_label_new (_("Skills & Experience"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label15);

  table_protections = gtk_table_new (6, 6, TRUE);
  gtk_widget_show (table_protections);
  gtk_container_add (GTK_CONTAINER (notebook3), table_protections);

  label16 = gtk_label_new (_("Protections"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label16);

  vpaned_info_inventory = gtk_vpaned_new ();
  gtk_widget_show (vpaned_info_inventory);
  gtk_paned_pack2 (GTK_PANED (hpaned_map_other), vpaned_info_inventory, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned_info_inventory), 300);

  vbox_info_entry = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_info_entry);
  gtk_paned_pack1 (GTK_PANED (vpaned_info_inventory), vbox_info_entry, FALSE, TRUE);

  notebook_info = gtk_notebook_new ();
  gtk_widget_show (notebook_info);
  gtk_box_pack_start (GTK_BOX (vbox_info_entry), notebook_info, TRUE, TRUE, 0);

  scrolledwindow_textview1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_textview1);
  gtk_container_add (GTK_CONTAINER (notebook_info), scrolledwindow_textview1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_textview1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  textview_info1 = gtk_text_view_new ();
  gtk_widget_show (textview_info1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_textview1), textview_info1);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview_info1), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview_info1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview_info1), FALSE);

  label1 = gtk_label_new (_("Messages"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_info), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_info), 0), label1);

  scrolledwindow_textview2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_textview2);
  gtk_container_add (GTK_CONTAINER (notebook_info), scrolledwindow_textview2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_textview2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  textview_info2 = gtk_text_view_new ();
  gtk_widget_show (textview_info2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_textview2), textview_info2);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview_info2), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview_info2), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview_info2), FALSE);

  label2 = gtk_label_new (_("Critical messages"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_info), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_info), 1), label2);

  entry_commands = gtk_entry_new ();
  gtk_widget_show (entry_commands);
  gtk_box_pack_start (GTK_BOX (vbox_info_entry), entry_commands, FALSE, FALSE, 0);

  vpaned_inv_look = gtk_vpaned_new ();
  gtk_widget_show (vpaned_inv_look);
  gtk_paned_pack2 (GTK_PANED (vpaned_info_inventory), vpaned_inv_look, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned_inv_look), 400);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_paned_pack1 (GTK_PANED (vpaned_inv_look), vbox3, FALSE, TRUE);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, FALSE, TRUE, 0);

  label3 = gtk_label_new (_("Inventory:"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 10);

  label_inv_weight = gtk_label_new (_("0/0"));
  gtk_widget_show (label_inv_weight);
  gtk_box_pack_start (GTK_BOX (hbox1), label_inv_weight, FALSE, FALSE, 15);

  label5 = gtk_label_new (_("Count"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 5);

  spinbutton_count_adj = gtk_adjustment_new (0, 0, 1000000, 1, 10, 10);
  spinbutton_count = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_count_adj), 1, 0);
  gtk_widget_show (spinbutton_count);
  gtk_box_pack_start (GTK_BOX (hbox1), spinbutton_count, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_count), TRUE);

  notebook_inv = gtk_notebook_new ();
  gtk_widget_show (notebook_inv);
  gtk_box_pack_start (GTK_BOX (vbox3), notebook_inv, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (notebook_inv, GTK_CAN_FOCUS);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook_inv), scrolledwindow6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), viewport1);
  GTK_WIDGET_SET_FLAGS (viewport1, GTK_CAN_FOCUS);

  inv_table = gtk_table_new (11, 10, FALSE);
  gtk_widget_show (inv_table);
  gtk_container_add (GTK_CONTAINER (viewport1), inv_table);
  GTK_WIDGET_SET_FLAGS (inv_table, GTK_CAN_FOCUS);

  label80 = gtk_label_new (_("Icons"));
  gtk_widget_show (label80);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook_inv), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook_inv), 0), label80);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_paned_pack2 (GTK_PANED (vpaned_inv_look), vbox4, TRUE, TRUE);

  label9 = gtk_label_new (_("You see:"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox4), label9, FALSE, FALSE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  treeview_look = gtk_tree_view_new ();
  gtk_widget_show (treeview_look);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview_look);

  g_signal_connect_swapped ((gpointer) window_root, "key_press_event",
                            G_CALLBACK (keyfunc),
                            GTK_OBJECT (window_root));
  g_signal_connect_swapped ((gpointer) window_root, "key_release_event",
                            G_CALLBACK (keyrelfunc),
                            GTK_OBJECT (window_root));
  g_signal_connect ((gpointer) window_root, "destroy",
                    G_CALLBACK (on_window_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) quit_character1, "activate",
                    G_CALLBACK (menu_quit_character),
                    NULL);
  g_signal_connect ((gpointer) quit2, "activate",
                    G_CALLBACK (menu_quit_program),
                    NULL);
  g_signal_connect ((gpointer) configure1, "activate",
                    G_CALLBACK (on_configure_activate),
                    NULL);
  g_signal_connect ((gpointer) disconnect, "activate",
                    G_CALLBACK (on_disconnect_activate),
                    NULL);
  g_signal_connect ((gpointer) keybindings, "activate",
                    G_CALLBACK (on_keybindings_activate),
                    NULL);
  g_signal_connect ((gpointer) save_window_position, "activate",
                    G_CALLBACK (on_save_window_position_activate),
                    NULL);
  g_signal_connect ((gpointer) spells, "activate",
                    G_CALLBACK (on_spells_activate),
                    NULL);
  g_signal_connect ((gpointer) don_t_pickup1, "activate",
                    G_CALLBACK (on_menu_dont_pickup_activate),
                    NULL);
  g_signal_connect ((gpointer) stop_before_pickup1, "activate",
                    G_CALLBACK (on_menu_stop_before_pickup_activate),
                    NULL);
  g_signal_connect ((gpointer) body_armor1, "activate",
                    G_CALLBACK (on_menu_body_armor_activate),
                    NULL);
  g_signal_connect ((gpointer) boots1, "activate",
                    G_CALLBACK (on_menu_boots_activate),
                    NULL);
  g_signal_connect ((gpointer) cloaks1, "activate",
                    G_CALLBACK (on_menu_cloaks_activate),
                    NULL);
  g_signal_connect ((gpointer) gloves1, "activate",
                    G_CALLBACK (on_menu_gloves_activate),
                    NULL);
  g_signal_connect ((gpointer) helmets1, "activate",
                    G_CALLBACK (on_menu_helmets_activate),
                    NULL);
  g_signal_connect ((gpointer) shields1, "activate",
                    G_CALLBACK (on_menu_shields_activate),
                    NULL);
  g_signal_connect ((gpointer) skillscrolls1, "activate",
                    G_CALLBACK (on_menu_skillscrolls_activate),
                    NULL);
  g_signal_connect ((gpointer) normal_book_scrolls1, "activate",
                    G_CALLBACK (on_menu_normal_book_scrolls_activate),
                    NULL);
  g_signal_connect ((gpointer) spellbooks1, "activate",
                    G_CALLBACK (on_menu_spellbooks_activate),
                    NULL);
  g_signal_connect ((gpointer) drinks1, "activate",
                    G_CALLBACK (on_menu_drinks_activate),
                    NULL);
  g_signal_connect ((gpointer) food1, "activate",
                    G_CALLBACK (on_menu_food_activate),
                    NULL);
  g_signal_connect ((gpointer) keys1, "activate",
                    G_CALLBACK (on_menu_keys_activate),
                    NULL);
  g_signal_connect ((gpointer) magical_items, "activate",
                    G_CALLBACK (on_menu_magical_items_activate),
                    NULL);
  g_signal_connect ((gpointer) potions, "activate",
                    G_CALLBACK (on_menu_potions_activate),
                    NULL);
  g_signal_connect ((gpointer) valuables, "activate",
                    G_CALLBACK (on_menu_valuables_activate),
                    NULL);
  g_signal_connect ((gpointer) wands_rods_horns, "activate",
                    G_CALLBACK (on_menu_wands_rods_horns_activate),
                    NULL);
  g_signal_connect ((gpointer) all_weapons, "activate",
                    G_CALLBACK (on_menu_all_weapons_activate),
                    NULL);
  g_signal_connect ((gpointer) missile_weapons1, "activate",
                    G_CALLBACK (on_menu_missile_weapons_activate),
                    NULL);
  g_signal_connect ((gpointer) bows1, "activate",
                    G_CALLBACK (on_menu_bows_activate),
                    NULL);
  g_signal_connect ((gpointer) arrows1, "activate",
                    G_CALLBACK (on_menu_arrows_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_pickup_off1, "activate",
                    G_CALLBACK (on_menu_ratio_pickup_off_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_5, "activate",
                    G_CALLBACK (on_menu_ratio_5_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_10, "activate",
                    G_CALLBACK (on_menu_ratio_10_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_15, "activate",
                    G_CALLBACK (on_menu_ratio_15_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_20, "activate",
                    G_CALLBACK (on_menu_ratio_20_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_25, "activate",
                    G_CALLBACK (on_menu_ratio_25_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_30, "activate",
                    G_CALLBACK (on_menu_ratio_35_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_35, "activate",
                    G_CALLBACK (on_menu_ratio_35_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_40, "activate",
                    G_CALLBACK (on_menu_ratio_40_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_45, "activate",
                    G_CALLBACK (on_menu_ratio_45_activate),
                    NULL);
  g_signal_connect ((gpointer) ratio_50, "activate",
                    G_CALLBACK (on_menu_ratio_50_activate),
                    NULL);
  g_signal_connect ((gpointer) not_cursed1, "activate",
                    G_CALLBACK (on_menu_not_cursed_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (menu_about),
                    NULL);
  g_signal_connect ((gpointer) drawingarea_map, "expose_event",
                    G_CALLBACK (on_drawingarea_map_expose_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea_map, "button_press_event",
                    G_CALLBACK (on_drawingarea_map_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawingarea_magic_map, "expose_event",
                    G_CALLBACK (on_drawingarea_magic_map_expose_event),
                    NULL);
  g_signal_connect ((gpointer) entry_commands, "activate",
                    G_CALLBACK (on_entry_commands_activate),
                    NULL);
  g_signal_connect ((gpointer) notebook_inv, "switch_page",
                    G_CALLBACK (on_notebook_switch_page),
                    NULL);
  g_signal_connect ((gpointer) inv_table, "expose_event",
                    G_CALLBACK (on_inv_table_expose_event),
                    NULL);
  g_signal_connect ((gpointer) treeview_look, "row_collapsed",
                    G_CALLBACK (list_row_collapse),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_root, window_root, "window_root");
  GLADE_HOOKUP_OBJECT (window_root, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_root, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_root, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window_root, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window_root, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window_root, quit_character1, "quit_character1");
  GLADE_HOOKUP_OBJECT (window_root, quit2, "quit2");
  GLADE_HOOKUP_OBJECT (window_root, client1, "client1");
  GLADE_HOOKUP_OBJECT (window_root, client1_menu, "client1_menu");
  GLADE_HOOKUP_OBJECT (window_root, configure1, "configure1");
  GLADE_HOOKUP_OBJECT (window_root, disconnect, "disconnect");
  GLADE_HOOKUP_OBJECT (window_root, keybindings, "keybindings");
  GLADE_HOOKUP_OBJECT (window_root, save_window_position, "save_window_position");
  GLADE_HOOKUP_OBJECT (window_root, menu_player, "menu_player");
  GLADE_HOOKUP_OBJECT (window_root, menu_player_menu, "menu_player_menu");
  GLADE_HOOKUP_OBJECT (window_root, spells, "spells");
  GLADE_HOOKUP_OBJECT (window_root, pickup1, "pickup1");
  GLADE_HOOKUP_OBJECT (window_root, pickup1_menu, "pickup1_menu");
  GLADE_HOOKUP_OBJECT (window_root, don_t_pickup1, "don_t_pickup1");
  GLADE_HOOKUP_OBJECT (window_root, stop_before_pickup1, "stop_before_pickup1");
  GLADE_HOOKUP_OBJECT (window_root, armor1, "armor1");
  GLADE_HOOKUP_OBJECT (window_root, armor1_menu, "armor1_menu");
  GLADE_HOOKUP_OBJECT (window_root, body_armor1, "body_armor1");
  GLADE_HOOKUP_OBJECT (window_root, boots1, "boots1");
  GLADE_HOOKUP_OBJECT (window_root, cloaks1, "cloaks1");
  GLADE_HOOKUP_OBJECT (window_root, gloves1, "gloves1");
  GLADE_HOOKUP_OBJECT (window_root, helmets1, "helmets1");
  GLADE_HOOKUP_OBJECT (window_root, shields1, "shields1");
  GLADE_HOOKUP_OBJECT (window_root, books1, "books1");
  GLADE_HOOKUP_OBJECT (window_root, books1_menu, "books1_menu");
  GLADE_HOOKUP_OBJECT (window_root, skillscrolls1, "skillscrolls1");
  GLADE_HOOKUP_OBJECT (window_root, normal_book_scrolls1, "normal_book_scrolls1");
  GLADE_HOOKUP_OBJECT (window_root, spellbooks1, "spellbooks1");
  GLADE_HOOKUP_OBJECT (window_root, drinks1, "drinks1");
  GLADE_HOOKUP_OBJECT (window_root, food1, "food1");
  GLADE_HOOKUP_OBJECT (window_root, keys1, "keys1");
  GLADE_HOOKUP_OBJECT (window_root, magical_items, "magical_items");
  GLADE_HOOKUP_OBJECT (window_root, potions, "potions");
  GLADE_HOOKUP_OBJECT (window_root, valuables, "valuables");
  GLADE_HOOKUP_OBJECT (window_root, wands_rods_horns, "wands_rods_horns");
  GLADE_HOOKUP_OBJECT (window_root, weapons1, "weapons1");
  GLADE_HOOKUP_OBJECT (window_root, weapons1_menu, "weapons1_menu");
  GLADE_HOOKUP_OBJECT (window_root, all_weapons, "all_weapons");
  GLADE_HOOKUP_OBJECT (window_root, missile_weapons1, "missile_weapons1");
  GLADE_HOOKUP_OBJECT (window_root, bows1, "bows1");
  GLADE_HOOKUP_OBJECT (window_root, arrows1, "arrows1");
  GLADE_HOOKUP_OBJECT (window_root, weight_value_1, "weight_value_1");
  GLADE_HOOKUP_OBJECT (window_root, weight_value_1_menu, "weight_value_1_menu");
  GLADE_HOOKUP_OBJECT (window_root, ratio_pickup_off1, "ratio_pickup_off1");
  GLADE_HOOKUP_OBJECT (window_root, ratio_5, "ratio_5");
  GLADE_HOOKUP_OBJECT (window_root, ratio_10, "ratio_10");
  GLADE_HOOKUP_OBJECT (window_root, ratio_15, "ratio_15");
  GLADE_HOOKUP_OBJECT (window_root, ratio_20, "ratio_20");
  GLADE_HOOKUP_OBJECT (window_root, ratio_25, "ratio_25");
  GLADE_HOOKUP_OBJECT (window_root, ratio_30, "ratio_30");
  GLADE_HOOKUP_OBJECT (window_root, ratio_35, "ratio_35");
  GLADE_HOOKUP_OBJECT (window_root, ratio_40, "ratio_40");
  GLADE_HOOKUP_OBJECT (window_root, ratio_45, "ratio_45");
  GLADE_HOOKUP_OBJECT (window_root, ratio_50, "ratio_50");
  GLADE_HOOKUP_OBJECT (window_root, not_cursed1, "not_cursed1");
  GLADE_HOOKUP_OBJECT (window_root, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window_root, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window_root, about1, "about1");
  GLADE_HOOKUP_OBJECT (window_root, fire_on, "fire_on");
  GLADE_HOOKUP_OBJECT (window_root, run_on, "run_on");
  GLADE_HOOKUP_OBJECT (window_root, filler, "filler");
  GLADE_HOOKUP_OBJECT (window_root, hpaned_map_other, "hpaned_map_other");
  GLADE_HOOKUP_OBJECT (window_root, vpaned_map_stats, "vpaned_map_stats");
  GLADE_HOOKUP_OBJECT (window_root, map_notebook, "map_notebook");
  GLADE_HOOKUP_OBJECT (window_root, table_map, "table_map");
  GLADE_HOOKUP_OBJECT (window_root, drawingarea_map, "drawingarea_map");
  GLADE_HOOKUP_OBJECT (window_root, button_map_recenter, "button_map_recenter");
  GLADE_HOOKUP_OBJECT (window_root, vscrollbar_map, "vscrollbar_map");
  GLADE_HOOKUP_OBJECT (window_root, hscrollbar_map, "hscrollbar_map");
  GLADE_HOOKUP_OBJECT (window_root, label46, "label46");
  GLADE_HOOKUP_OBJECT (window_root, drawingarea_magic_map, "drawingarea_magic_map");
  GLADE_HOOKUP_OBJECT (window_root, label47, "label47");
  GLADE_HOOKUP_OBJECT (window_root, hpaned_statbar_stats, "hpaned_statbar_stats");
  GLADE_HOOKUP_OBJECT (window_root, table4, "table4");
  GLADE_HOOKUP_OBJECT (window_root, label_stats_hp, "label_stats_hp");
  GLADE_HOOKUP_OBJECT (window_root, label_stats_sp, "label_stats_sp");
  GLADE_HOOKUP_OBJECT (window_root, label_stats_grace, "label_stats_grace");
  GLADE_HOOKUP_OBJECT (window_root, label_stats_food, "label_stats_food");
  GLADE_HOOKUP_OBJECT (window_root, progressbar_hp, "progressbar_hp");
  GLADE_HOOKUP_OBJECT (window_root, progressbar_sp, "progressbar_sp");
  GLADE_HOOKUP_OBJECT (window_root, progressbar_grace, "progressbar_grace");
  GLADE_HOOKUP_OBJECT (window_root, progressbar_food, "progressbar_food");
  GLADE_HOOKUP_OBJECT (window_root, fire_label, "fire_label");
  GLADE_HOOKUP_OBJECT (window_root, run_label, "run_label");
  GLADE_HOOKUP_OBJECT (window_root, label_stats_exp, "label_stats_exp");
  GLADE_HOOKUP_OBJECT (window_root, progressbar_exp, "progressbar_exp");
  GLADE_HOOKUP_OBJECT (window_root, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (window_root, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (window_root, label_playername, "label_playername");
  GLADE_HOOKUP_OBJECT (window_root, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_root, label49, "label49");
  GLADE_HOOKUP_OBJECT (window_root, label_str, "label_str");
  GLADE_HOOKUP_OBJECT (window_root, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_root, label_dex, "label_dex");
  GLADE_HOOKUP_OBJECT (window_root, label53, "label53");
  GLADE_HOOKUP_OBJECT (window_root, label_con, "label_con");
  GLADE_HOOKUP_OBJECT (window_root, label55, "label55");
  GLADE_HOOKUP_OBJECT (window_root, label_int, "label_int");
  GLADE_HOOKUP_OBJECT (window_root, label57, "label57");
  GLADE_HOOKUP_OBJECT (window_root, label_wis, "label_wis");
  GLADE_HOOKUP_OBJECT (window_root, label59, "label59");
  GLADE_HOOKUP_OBJECT (window_root, label_pow, "label_pow");
  GLADE_HOOKUP_OBJECT (window_root, label61, "label61");
  GLADE_HOOKUP_OBJECT (window_root, label_cha, "label_cha");
  GLADE_HOOKUP_OBJECT (window_root, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_root, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_root, label_wc, "label_wc");
  GLADE_HOOKUP_OBJECT (window_root, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_root, label_dam, "label_dam");
  GLADE_HOOKUP_OBJECT (window_root, label36, "label36");
  GLADE_HOOKUP_OBJECT (window_root, label_ac, "label_ac");
  GLADE_HOOKUP_OBJECT (window_root, label38, "label38");
  GLADE_HOOKUP_OBJECT (window_root, label_armor, "label_armor");
  GLADE_HOOKUP_OBJECT (window_root, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_root, label64, "label64");
  GLADE_HOOKUP_OBJECT (window_root, label_speed, "label_speed");
  GLADE_HOOKUP_OBJECT (window_root, label66, "label66");
  GLADE_HOOKUP_OBJECT (window_root, label_weapon_speed, "label_weapon_speed");
  GLADE_HOOKUP_OBJECT (window_root, label_range, "label_range");
  GLADE_HOOKUP_OBJECT (window_root, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_root, label_exp, "label_exp");
  GLADE_HOOKUP_OBJECT (window_root, label_level, "label_level");
  GLADE_HOOKUP_OBJECT (window_root, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_root, table_skills_exp, "table_skills_exp");
  GLADE_HOOKUP_OBJECT (window_root, label15, "label15");
  GLADE_HOOKUP_OBJECT (window_root, table_protections, "table_protections");
  GLADE_HOOKUP_OBJECT (window_root, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_root, vpaned_info_inventory, "vpaned_info_inventory");
  GLADE_HOOKUP_OBJECT (window_root, vbox_info_entry, "vbox_info_entry");
  GLADE_HOOKUP_OBJECT (window_root, notebook_info, "notebook_info");
  GLADE_HOOKUP_OBJECT (window_root, scrolledwindow_textview1, "scrolledwindow_textview1");
  GLADE_HOOKUP_OBJECT (window_root, textview_info1, "textview_info1");
  GLADE_HOOKUP_OBJECT (window_root, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_root, scrolledwindow_textview2, "scrolledwindow_textview2");
  GLADE_HOOKUP_OBJECT (window_root, textview_info2, "textview_info2");
  GLADE_HOOKUP_OBJECT (window_root, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_root, entry_commands, "entry_commands");
  GLADE_HOOKUP_OBJECT (window_root, vpaned_inv_look, "vpaned_inv_look");
  GLADE_HOOKUP_OBJECT (window_root, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window_root, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_root, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_root, label_inv_weight, "label_inv_weight");
  GLADE_HOOKUP_OBJECT (window_root, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_root, spinbutton_count, "spinbutton_count");
  GLADE_HOOKUP_OBJECT (window_root, notebook_inv, "notebook_inv");
  GLADE_HOOKUP_OBJECT (window_root, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (window_root, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window_root, inv_table, "inv_table");
  GLADE_HOOKUP_OBJECT (window_root, label80, "label80");
  GLADE_HOOKUP_OBJECT (window_root, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window_root, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_root, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window_root, treeview_look, "treeview_look");

  return window_root;
}

GtkWidget*
create_metaserver_window (void)
{
  GtkWidget *metaserver_window;
  GtkWidget *vbox7;
  GtkWidget *label83;
  GtkWidget *scrolledwindow7;
  GtkWidget *treeview_metaserver;
  GtkWidget *hbox12;
  GtkWidget *label84;
  GtkWidget *metaserver_text_entry;
  GtkWidget *hbox10;
  GtkWidget *label81;
  GtkWidget *metaserver_status;
  GtkWidget *hbox11;
  GtkWidget *metaserver_select;
  GtkWidget *button_metaserver_quit;

  metaserver_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  GTK_WIDGET_SET_FLAGS (metaserver_window, GTK_CAN_FOCUS);
  gtk_window_set_title (GTK_WINDOW (metaserver_window), _("Metaserver Selection"));
  gtk_window_set_position (GTK_WINDOW (metaserver_window), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_default_size (GTK_WINDOW (metaserver_window), 805, 400);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (metaserver_window), vbox7);

  label83 = gtk_label_new (_("Please Select a Server to Play On"));
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (vbox7), label83, FALSE, FALSE, 0);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow7, TRUE, TRUE, 0);

  treeview_metaserver = gtk_tree_view_new ();
  gtk_widget_show (treeview_metaserver);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), treeview_metaserver);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox12, FALSE, FALSE, 0);

  label84 = gtk_label_new (_("Or enter server name:"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox12), label84, FALSE, FALSE, 0);

  metaserver_text_entry = gtk_entry_new ();
  gtk_widget_show (metaserver_text_entry);
  gtk_box_pack_start (GTK_BOX (hbox12), metaserver_text_entry, TRUE, TRUE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox10, FALSE, FALSE, 0);

  label81 = gtk_label_new (_("Status:"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox10), label81, FALSE, FALSE, 0);

  metaserver_status = gtk_label_new ("");
  gtk_widget_show (metaserver_status);
  gtk_box_pack_start (GTK_BOX (hbox10), metaserver_status, FALSE, FALSE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox11, FALSE, TRUE, 0);

  metaserver_select = gtk_button_new_with_mnemonic (_("Connect"));
  gtk_widget_show (metaserver_select);
  gtk_box_pack_start (GTK_BOX (hbox11), metaserver_select, TRUE, FALSE, 0);
  gtk_widget_set_sensitive (metaserver_select, FALSE);
  GTK_WIDGET_UNSET_FLAGS (metaserver_select, GTK_CAN_FOCUS);

  button_metaserver_quit = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (button_metaserver_quit);
  gtk_box_pack_start (GTK_BOX (hbox11), button_metaserver_quit, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) metaserver_window, "destroy",
                    G_CALLBACK (on_window_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) treeview_metaserver, "row_activated",
                    G_CALLBACK (on_treeview_metaserver_row_activated),
                    NULL);
  g_signal_connect ((gpointer) metaserver_text_entry, "activate",
                    G_CALLBACK (on_metaserver_text_entry_activate),
                    NULL);
  g_signal_connect ((gpointer) metaserver_text_entry, "key_press_event",
                    G_CALLBACK (on_metaserver_text_entry_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) metaserver_select, "clicked",
                    G_CALLBACK (on_metaserver_select_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_metaserver_quit, "pressed",
                    G_CALLBACK (on_button_metaserver_quit_pressed),
                    NULL);
  g_signal_connect ((gpointer) button_metaserver_quit, "activate",
                    G_CALLBACK (on_button_metaserver_quit_pressed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (metaserver_window, metaserver_window, "metaserver_window");
  GLADE_HOOKUP_OBJECT (metaserver_window, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (metaserver_window, label83, "label83");
  GLADE_HOOKUP_OBJECT (metaserver_window, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (metaserver_window, treeview_metaserver, "treeview_metaserver");
  GLADE_HOOKUP_OBJECT (metaserver_window, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (metaserver_window, label84, "label84");
  GLADE_HOOKUP_OBJECT (metaserver_window, metaserver_text_entry, "metaserver_text_entry");
  GLADE_HOOKUP_OBJECT (metaserver_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (metaserver_window, label81, "label81");
  GLADE_HOOKUP_OBJECT (metaserver_window, metaserver_status, "metaserver_status");
  GLADE_HOOKUP_OBJECT (metaserver_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (metaserver_window, metaserver_select, "metaserver_select");
  GLADE_HOOKUP_OBJECT (metaserver_window, button_metaserver_quit, "button_metaserver_quit");

  return metaserver_window;
}

GtkWidget*
create_keybinding_window (void)
{
  GtkWidget *keybinding_window;
  GtkWidget *vbox8;
  GtkWidget *scrolledwindow8;
  GtkWidget *keybinding_treeview;
  GtkWidget *label85;
  GtkWidget *hbox13;
  GtkWidget *keybinding_checkbutton_control;
  GtkWidget *keybinding_checkbutton_shift;
  GtkWidget *keybinding_checkbutton_alt;
  GtkWidget *keybinding_checkbutton_meta;
  GtkWidget *keybinding_checkbutton_stayinedit;
  AtkObject *atko;
  GtkWidget *hbox14;
  GtkWidget *label86;
  GtkWidget *keybinding_entry_key;
  GtkWidget *label87;
  GtkWidget *keybinding_entry_command;
  GtkWidget *hbox15;
  GtkWidget *keybinding_button_remove;
  GtkWidget *keybinding_button_update;
  GtkWidget *keybinding_button_bind;
  GtkWidget *keybinding_button_clear;
  GtkWidget *keybinding_button_close;

  keybinding_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (keybinding_window, -1, 600);
  gtk_window_set_title (GTK_WINDOW (keybinding_window), _("Keybindings"));
  gtk_window_set_position (GTK_WINDOW (keybinding_window), GTK_WIN_POS_CENTER_ON_PARENT);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (keybinding_window), vbox8);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow8, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_SHADOW_IN);

  keybinding_treeview = gtk_tree_view_new ();
  gtk_widget_show (keybinding_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), keybinding_treeview);
  GTK_WIDGET_UNSET_FLAGS (keybinding_treeview, GTK_CAN_FOCUS);

  label85 = gtk_label_new (_("Keybinding Modfiers:"));
  gtk_widget_show (label85);
  gtk_box_pack_start (GTK_BOX (vbox8), label85, FALSE, FALSE, 0);

  hbox13 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox13, FALSE, TRUE, 0);

  keybinding_checkbutton_control = gtk_check_button_new_with_mnemonic (_("Run"));
  gtk_widget_show (keybinding_checkbutton_control);
  gtk_box_pack_start (GTK_BOX (hbox13), keybinding_checkbutton_control, FALSE, FALSE, 0);

  keybinding_checkbutton_shift = gtk_check_button_new_with_mnemonic (_("Fire"));
  gtk_widget_show (keybinding_checkbutton_shift);
  gtk_box_pack_start (GTK_BOX (hbox13), keybinding_checkbutton_shift, FALSE, FALSE, 0);

  keybinding_checkbutton_alt = gtk_check_button_new_with_mnemonic (_("Alt"));
  gtk_widget_show (keybinding_checkbutton_alt);
  gtk_box_pack_start (GTK_BOX (hbox13), keybinding_checkbutton_alt, FALSE, FALSE, 0);

  keybinding_checkbutton_meta = gtk_check_button_new_with_mnemonic (_("Meta"));
  gtk_widget_show (keybinding_checkbutton_meta);
  gtk_box_pack_start (GTK_BOX (hbox13), keybinding_checkbutton_meta, FALSE, FALSE, 0);

  keybinding_checkbutton_stayinedit = gtk_check_button_new_with_mnemonic (_("Stay in Edit Mode"));
  gtk_widget_show (keybinding_checkbutton_stayinedit);
  gtk_box_pack_start (GTK_BOX (hbox13), keybinding_checkbutton_stayinedit, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox14, FALSE, TRUE, 0);

  label86 = gtk_label_new (_("Key:"));
  gtk_widget_show (label86);
  gtk_box_pack_start (GTK_BOX (hbox14), label86, FALSE, FALSE, 0);

  keybinding_entry_key = gtk_entry_new ();
  gtk_widget_show (keybinding_entry_key);
  gtk_box_pack_start (GTK_BOX (hbox14), keybinding_entry_key, TRUE, TRUE, 11);

  label87 = gtk_label_new (_("Command"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox14), label87, FALSE, FALSE, 0);

  keybinding_entry_command = gtk_entry_new ();
  gtk_widget_show (keybinding_entry_command);
  gtk_box_pack_start (GTK_BOX (hbox14), keybinding_entry_command, TRUE, TRUE, 5);

  hbox15 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox15, FALSE, TRUE, 0);

  keybinding_button_remove = gtk_button_new_with_mnemonic (_("Remove Keybinding"));
  gtk_widget_show (keybinding_button_remove);
  gtk_box_pack_start (GTK_BOX (hbox15), keybinding_button_remove, FALSE, FALSE, 0);

  keybinding_button_update = gtk_button_new_with_mnemonic (_("Update Binding"));
  gtk_widget_show (keybinding_button_update);
  gtk_box_pack_start (GTK_BOX (hbox15), keybinding_button_update, FALSE, FALSE, 0);

  keybinding_button_bind = gtk_button_new_with_mnemonic (_("Add"));
  gtk_widget_show (keybinding_button_bind);
  gtk_box_pack_start (GTK_BOX (hbox15), keybinding_button_bind, FALSE, FALSE, 0);

  keybinding_button_clear = gtk_button_new_with_mnemonic (_("Clear Fields"));
  gtk_widget_show (keybinding_button_clear);
  gtk_box_pack_start (GTK_BOX (hbox15), keybinding_button_clear, FALSE, FALSE, 0);

  keybinding_button_close = gtk_button_new_with_mnemonic (_("Close Window"));
  gtk_widget_show (keybinding_button_close);
  gtk_box_pack_start (GTK_BOX (hbox15), keybinding_button_close, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) keybinding_entry_key, "key_press_event",
                    G_CALLBACK (on_keybinding_entry_key_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) keybinding_button_remove, "clicked",
                    G_CALLBACK (on_keybinding_button_remove_clicked),
                    NULL);
  g_signal_connect ((gpointer) keybinding_button_update, "clicked",
                    G_CALLBACK (on_keybinding_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) keybinding_button_bind, "clicked",
                    G_CALLBACK (on_keybinding_button_bind_clicked),
                    NULL);
  g_signal_connect ((gpointer) keybinding_button_clear, "clicked",
                    G_CALLBACK (on_keybinding_button_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) keybinding_button_close, "clicked",
                    G_CALLBACK (on_keybinding_button_close_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (keybinding_checkbutton_stayinedit);
  atk_object_set_description (atko, _("Keybinding will not be executed immediately - instead, will stay in edit mode so additional text can be entered before command is executed."));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (keybinding_window, keybinding_window, "keybinding_window");
  GLADE_HOOKUP_OBJECT (keybinding_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (keybinding_window, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_treeview, "keybinding_treeview");
  GLADE_HOOKUP_OBJECT (keybinding_window, label85, "label85");
  GLADE_HOOKUP_OBJECT (keybinding_window, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_checkbutton_control, "keybinding_checkbutton_control");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_checkbutton_shift, "keybinding_checkbutton_shift");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_checkbutton_alt, "keybinding_checkbutton_alt");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_checkbutton_meta, "keybinding_checkbutton_meta");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_checkbutton_stayinedit, "keybinding_checkbutton_stayinedit");
  GLADE_HOOKUP_OBJECT (keybinding_window, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (keybinding_window, label86, "label86");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_entry_key, "keybinding_entry_key");
  GLADE_HOOKUP_OBJECT (keybinding_window, label87, "label87");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_entry_command, "keybinding_entry_command");
  GLADE_HOOKUP_OBJECT (keybinding_window, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_button_remove, "keybinding_button_remove");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_button_update, "keybinding_button_update");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_button_bind, "keybinding_button_bind");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_button_clear, "keybinding_button_clear");
  GLADE_HOOKUP_OBJECT (keybinding_window, keybinding_button_close, "keybinding_button_close");

  return keybinding_window;
}

GtkWidget*
create_spell_window (void)
{
  GtkWidget *spell_window;
  GtkWidget *vbox9;
  GtkWidget *scrolledwindow9;
  GtkWidget *spell_treeview;
  GtkWidget *hbox17;
  GtkWidget *spell_drawingarea_attuned;
  GtkWidget *spell_label_green;
  GtkWidget *spell_drawingarea_repelled;
  GtkWidget *spell_label_orange;
  GtkWidget *spell_drawingarea_denied;
  GtkWidget *spell_label_red;
  GtkWidget *label91;
  GtkWidget *spell_options;
  GtkWidget *hbox16;
  GtkWidget *spell_cast;
  GtkWidget *spell_invoke;
  GtkWidget *spell_close;

  spell_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (spell_window), _("Spell Information"));
  gtk_window_set_position (GTK_WINDOW (spell_window), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_default_size (GTK_WINDOW (spell_window), 800, 600);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (spell_window), vbox9);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_box_pack_start (GTK_BOX (vbox9), scrolledwindow9, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_SHADOW_IN);

  spell_treeview = gtk_tree_view_new ();
  gtk_widget_show (spell_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), spell_treeview);
  GTK_WIDGET_UNSET_FLAGS (spell_treeview, GTK_CAN_FOCUS);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox17, FALSE, TRUE, 0);

  spell_drawingarea_attuned = gtk_drawing_area_new ();
  gtk_widget_show (spell_drawingarea_attuned);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_drawingarea_attuned, FALSE, TRUE, 0);
  gtk_widget_set_size_request (spell_drawingarea_attuned, 30, -1);

  spell_label_green = gtk_label_new (_("Attuned"));
  gtk_widget_show (spell_label_green);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_label_green, FALSE, FALSE, 5);

  spell_drawingarea_repelled = gtk_drawing_area_new ();
  gtk_widget_show (spell_drawingarea_repelled);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_drawingarea_repelled, FALSE, TRUE, 0);
  gtk_widget_set_size_request (spell_drawingarea_repelled, 30, -1);

  spell_label_orange = gtk_label_new (_("Repelled"));
  gtk_widget_show (spell_label_orange);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_label_orange, FALSE, FALSE, 5);

  spell_drawingarea_denied = gtk_drawing_area_new ();
  gtk_widget_show (spell_drawingarea_denied);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_drawingarea_denied, FALSE, TRUE, 0);
  gtk_widget_set_size_request (spell_drawingarea_denied, 30, -1);

  spell_label_red = gtk_label_new (_("Denied"));
  gtk_widget_show (spell_label_red);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_label_red, FALSE, FALSE, 5);

  label91 = gtk_label_new (_("     Spell Options"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox17), label91, FALSE, FALSE, 5);

  spell_options = gtk_entry_new ();
  gtk_widget_show (spell_options);
  gtk_box_pack_start (GTK_BOX (hbox17), spell_options, TRUE, TRUE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox16, FALSE, TRUE, 0);

  spell_cast = gtk_button_new_with_mnemonic (_("Cast"));
  gtk_widget_show (spell_cast);
  gtk_box_pack_start (GTK_BOX (hbox16), spell_cast, TRUE, FALSE, 0);

  spell_invoke = gtk_button_new_with_mnemonic (_("Invoke"));
  gtk_widget_show (spell_invoke);
  gtk_box_pack_start (GTK_BOX (hbox16), spell_invoke, TRUE, FALSE, 0);

  spell_close = gtk_button_new_with_mnemonic (_("Close Window"));
  gtk_widget_show (spell_close);
  gtk_box_pack_start (GTK_BOX (hbox16), spell_close, TRUE, FALSE, 0);

  g_signal_connect ((gpointer) spell_treeview, "row_activated",
                    G_CALLBACK (on_spell_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) spell_cast, "clicked",
                    G_CALLBACK (on_spell_cast_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_invoke, "clicked",
                    G_CALLBACK (on_spell_invoke_clicked),
                    NULL);
  g_signal_connect ((gpointer) spell_close, "clicked",
                    G_CALLBACK (on_spell_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (spell_window, spell_window, "spell_window");
  GLADE_HOOKUP_OBJECT (spell_window, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (spell_window, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (spell_window, spell_treeview, "spell_treeview");
  GLADE_HOOKUP_OBJECT (spell_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (spell_window, spell_drawingarea_attuned, "spell_drawingarea_attuned");
  GLADE_HOOKUP_OBJECT (spell_window, spell_label_green, "spell_label_green");
  GLADE_HOOKUP_OBJECT (spell_window, spell_drawingarea_repelled, "spell_drawingarea_repelled");
  GLADE_HOOKUP_OBJECT (spell_window, spell_label_orange, "spell_label_orange");
  GLADE_HOOKUP_OBJECT (spell_window, spell_drawingarea_denied, "spell_drawingarea_denied");
  GLADE_HOOKUP_OBJECT (spell_window, spell_label_red, "spell_label_red");
  GLADE_HOOKUP_OBJECT (spell_window, label91, "label91");
  GLADE_HOOKUP_OBJECT (spell_window, spell_options, "spell_options");
  GLADE_HOOKUP_OBJECT (spell_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (spell_window, spell_cast, "spell_cast");
  GLADE_HOOKUP_OBJECT (spell_window, spell_invoke, "spell_invoke");
  GLADE_HOOKUP_OBJECT (spell_window, spell_close, "spell_close");

  return spell_window;
}

GtkWidget*
create_config_window (void)
{
  GtkWidget *config_window;
  GtkWidget *vbox10;
  GtkWidget *hbox19;
  GtkWidget *label95;
  GtkWidget *hseparator1;
  GtkWidget *config_button_foodbeep;
  GtkWidget *hbox18;
  GtkObject *config_spinbutton_cwindow_adj;
  GtkWidget *config_spinbutton_cwindow;
  GtkWidget *label94;
  GtkWidget *config_button_echo;
  GtkWidget *config_button_fasttcp;
  GtkWidget *config_button_grad_color;
  GtkWidget *config_button_sound;
  GtkWidget *hbox20;
  GtkWidget *label96;
  GtkWidget *hseparator2;
  GtkWidget *config_button_cache;
  GtkWidget *config_button_download;
  GtkWidget *config_button_fog;
  GtkWidget *hbox21;
  GtkObject *config_spinbutton_iconscale_adj;
  GtkWidget *config_spinbutton_iconscale;
  GtkWidget *label97;
  GtkWidget *hbox22;
  GtkObject *config_spinbutton_mapscale_adj;
  GtkWidget *config_spinbutton_mapscale;
  GtkWidget *label98;
  GtkWidget *config_button_smoothing;
  GtkWidget *hbox23;
  GtkWidget *config_combobox_displaymode;
  GtkWidget *label99;
  GtkWidget *hbox24;
  GtkWidget *config_combobox_lighting;
  GtkWidget *label100;
  GtkWidget *hbox28;
  GtkWidget *vbox11;
  GtkWidget *hbox25;
  GtkObject *config_spinbutton_mapwidth_adj;
  GtkWidget *config_spinbutton_mapwidth;
  GtkWidget *label101;
  GtkWidget *hbox27;
  GtkObject *config_spinbutton_mapheight_adj;
  GtkWidget *config_spinbutton_mapheight;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *hbox26;
  GtkWidget *config_combobox_faceset;
  GtkWidget *label102;
  GtkWidget *hseparator3;
  GtkWidget *hbuttonbox1;
  GtkWidget *config_button_save;
  GtkWidget *config_button_apply;
  GtkWidget *config_button_close;

  config_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (config_window), _("Configuration Window"));
  gtk_window_set_position (GTK_WINDOW (config_window), GTK_WIN_POS_CENTER_ON_PARENT);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (config_window), vbox10);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox19, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox19), 5);

  label95 = gtk_label_new (_("General Options"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox19), label95, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (hbox19), hseparator1, TRUE, TRUE, 0);

  config_button_foodbeep = gtk_check_button_new_with_mnemonic (_("Beep When Food is Low"));
  gtk_widget_show (config_button_foodbeep);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_foodbeep, FALSE, FALSE, 0);

  hbox18 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox18, FALSE, TRUE, 0);

  config_spinbutton_cwindow_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  config_spinbutton_cwindow = gtk_spin_button_new (GTK_ADJUSTMENT (config_spinbutton_cwindow_adj), 1, 0);
  gtk_widget_show (config_spinbutton_cwindow);
  gtk_box_pack_start (GTK_BOX (hbox18), config_spinbutton_cwindow, FALSE, TRUE, 0);

  label94 = gtk_label_new (_("Command Window"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox18), label94, FALSE, FALSE, 0);

  config_button_echo = gtk_check_button_new_with_mnemonic (_("Echo Bound Commands"));
  gtk_widget_show (config_button_echo);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_echo, FALSE, FALSE, 0);

  config_button_fasttcp = gtk_check_button_new_with_mnemonic (_("Fast TCP Send (May decrease latency at expense of using more outgoing bandwidth)"));
  gtk_widget_show (config_button_fasttcp);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_fasttcp, FALSE, FALSE, 0);

  config_button_grad_color = gtk_check_button_new_with_mnemonic (_("Gradually change stat bar color based on value of the stat.  Uses slightly more CPU time."));
  gtk_widget_show (config_button_grad_color);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_grad_color, FALSE, FALSE, 0);

  config_button_sound = gtk_check_button_new_with_mnemonic (_("Enable Sound Support"));
  gtk_widget_show (config_button_sound);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_sound, FALSE, FALSE, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox20, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox20), 5);

  label96 = gtk_label_new (_("Map & Image Options"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox20), label96, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (hbox20), hseparator2, TRUE, TRUE, 0);

  config_button_cache = gtk_check_button_new_with_mnemonic (_("Cache Images (Decreases bandwidth needed, but requires more local diskspace and some spaces may\n appear with ? until image is downloaded)"));
  gtk_widget_show (config_button_cache);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_cache, FALSE, FALSE, 0);

  config_button_download = gtk_check_button_new_with_mnemonic (_("Download all images from server at connection time.  This is used in conjunction with Cache Images and\nwill prevent the ? on the map.  This does increase startup/connectin time however"));
  gtk_widget_show (config_button_download);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_download, FALSE, FALSE, 0);

  config_button_fog = gtk_check_button_new_with_mnemonic (_("Enables fog of war - spaces no longer in view will appear greyed out instead\nof being drawn as black spaces."));
  gtk_widget_show (config_button_fog);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_fog, FALSE, FALSE, 0);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox21, FALSE, TRUE, 0);

  config_spinbutton_iconscale_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  config_spinbutton_iconscale = gtk_spin_button_new (GTK_ADJUSTMENT (config_spinbutton_iconscale_adj), 1, 0);
  gtk_widget_show (config_spinbutton_iconscale);
  gtk_box_pack_start (GTK_BOX (hbox21), config_spinbutton_iconscale, FALSE, TRUE, 0);

  label97 = gtk_label_new (_("Icon Scale (Takes effect next run)"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox21), label97, FALSE, FALSE, 5);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox22, FALSE, TRUE, 0);

  config_spinbutton_mapscale_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  config_spinbutton_mapscale = gtk_spin_button_new (GTK_ADJUSTMENT (config_spinbutton_mapscale_adj), 1, 0);
  gtk_widget_show (config_spinbutton_mapscale);
  gtk_box_pack_start (GTK_BOX (hbox22), config_spinbutton_mapscale, FALSE, TRUE, 0);

  label98 = gtk_label_new (_("Map Scale (Takes effect next run)"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox22), label98, FALSE, FALSE, 5);

  config_button_smoothing = gtk_check_button_new_with_mnemonic (_("Enable smoothing - map looks nicer, but requires more CPU time and bandwidth"));
  gtk_widget_show (config_button_smoothing);
  gtk_box_pack_start (GTK_BOX (vbox10), config_button_smoothing, FALSE, FALSE, 0);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox23, FALSE, TRUE, 0);

  config_combobox_displaymode = gtk_combo_box_new_text ();
  gtk_widget_show (config_combobox_displaymode);
  gtk_box_pack_start (GTK_BOX (hbox23), config_combobox_displaymode, FALSE, TRUE, 0);
  gtk_widget_set_size_request (config_combobox_displaymode, 170, -1);

  label99 = gtk_label_new (_("Display mode.  OpenGL provides best quality with least amount of CPU\nresources.  SDL is next best, followed by Pixmap.  Depending on your\nwindow system and available libraries, all of these may not be available."));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox23), label99, FALSE, FALSE, 6);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox24, FALSE, TRUE, 0);

  config_combobox_lighting = gtk_combo_box_new_text ();
  gtk_widget_show (config_combobox_lighting);
  gtk_box_pack_start (GTK_BOX (hbox24), config_combobox_lighting, FALSE, FALSE, 0);
  gtk_widget_set_size_request (config_combobox_lighting, 170, -1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (config_combobox_lighting), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (config_combobox_lighting), _("Best Per Pixel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (config_combobox_lighting), _("Fast Per Pixel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (config_combobox_lighting), _("Per Tile"));

  label100 = gtk_label_new (_("Lighting options.  These are only used with SDL display mode.  OpenGL\nuses its own best lighting method, and Pixmap mode will always use per\ntile lighting.  Best per pixel gives best result but is slowest.  Tile is fastest,\nbut has worst quality.  Selecting none only affects how the objects are drawn\non the client.  The server will still calculate what is visible based on light levels"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox24), label100, FALSE, FALSE, 5);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox28, FALSE, TRUE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox28), vbox11, TRUE, TRUE, 0);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox25);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox25, TRUE, TRUE, 0);

  config_spinbutton_mapwidth_adj = gtk_adjustment_new (25, 11, 25, 1, 10, 10);
  config_spinbutton_mapwidth = gtk_spin_button_new (GTK_ADJUSTMENT (config_spinbutton_mapwidth_adj), 1, 0);
  gtk_widget_show (config_spinbutton_mapwidth);
  gtk_box_pack_start (GTK_BOX (hbox25), config_spinbutton_mapwidth, FALSE, TRUE, 0);

  label101 = gtk_label_new (_("Map Width"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox25), label101, FALSE, FALSE, 5);

  hbox27 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox27);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox27, TRUE, TRUE, 0);

  config_spinbutton_mapheight_adj = gtk_adjustment_new (25, 11, 25, 1, 10, 10);
  config_spinbutton_mapheight = gtk_spin_button_new (GTK_ADJUSTMENT (config_spinbutton_mapheight_adj), 1, 0);
  gtk_widget_show (config_spinbutton_mapheight);
  gtk_box_pack_start (GTK_BOX (hbox27), config_spinbutton_mapheight, FALSE, TRUE, 0);

  label103 = gtk_label_new (_("Map Height"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox27), label103, FALSE, FALSE, 5);

  label104 = gtk_label_new (_("Map Size - Larger map gives more information, but uses more CPU and bandwidth\nChanging either width or height will not take effect until next server connection."));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox28), label104, TRUE, FALSE, 0);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox26, TRUE, FALSE, 0);

  config_combobox_faceset = gtk_combo_box_new_text ();
  gtk_widget_show (config_combobox_faceset);
  gtk_box_pack_start (GTK_BOX (hbox26), config_combobox_faceset, FALSE, TRUE, 0);
  gtk_widget_set_size_request (config_combobox_faceset, 170, -1);

  label102 = gtk_label_new (_("Face set to use.  Will take effect on next server connection.  Different facesets\nhave different styles."));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox26), label102, FALSE, FALSE, 5);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox10), hseparator3, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox10), hbuttonbox1, FALSE, TRUE, 0);

  config_button_save = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_show (config_button_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), config_button_save);
  GTK_WIDGET_SET_FLAGS (config_button_save, GTK_CAN_DEFAULT);

  config_button_apply = gtk_button_new_with_mnemonic (_("Apply"));
  gtk_widget_show (config_button_apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), config_button_apply);
  GTK_WIDGET_SET_FLAGS (config_button_apply, GTK_CAN_DEFAULT);

  config_button_close = gtk_button_new_with_mnemonic (_("Close Window"));
  gtk_widget_show (config_button_close);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), config_button_close);
  GTK_WIDGET_SET_FLAGS (config_button_close, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) config_button_save, "clicked",
                    G_CALLBACK (on_config_button_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) config_button_apply, "clicked",
                    G_CALLBACK (on_config_button_apply_clicked),
                    NULL);
  g_signal_connect ((gpointer) config_button_close, "clicked",
                    G_CALLBACK (on_config_button_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (config_window, config_window, "config_window");
  GLADE_HOOKUP_OBJECT (config_window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (config_window, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (config_window, label95, "label95");
  GLADE_HOOKUP_OBJECT (config_window, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (config_window, config_button_foodbeep, "config_button_foodbeep");
  GLADE_HOOKUP_OBJECT (config_window, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (config_window, config_spinbutton_cwindow, "config_spinbutton_cwindow");
  GLADE_HOOKUP_OBJECT (config_window, label94, "label94");
  GLADE_HOOKUP_OBJECT (config_window, config_button_echo, "config_button_echo");
  GLADE_HOOKUP_OBJECT (config_window, config_button_fasttcp, "config_button_fasttcp");
  GLADE_HOOKUP_OBJECT (config_window, config_button_grad_color, "config_button_grad_color");
  GLADE_HOOKUP_OBJECT (config_window, config_button_sound, "config_button_sound");
  GLADE_HOOKUP_OBJECT (config_window, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (config_window, label96, "label96");
  GLADE_HOOKUP_OBJECT (config_window, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (config_window, config_button_cache, "config_button_cache");
  GLADE_HOOKUP_OBJECT (config_window, config_button_download, "config_button_download");
  GLADE_HOOKUP_OBJECT (config_window, config_button_fog, "config_button_fog");
  GLADE_HOOKUP_OBJECT (config_window, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (config_window, config_spinbutton_iconscale, "config_spinbutton_iconscale");
  GLADE_HOOKUP_OBJECT (config_window, label97, "label97");
  GLADE_HOOKUP_OBJECT (config_window, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (config_window, config_spinbutton_mapscale, "config_spinbutton_mapscale");
  GLADE_HOOKUP_OBJECT (config_window, label98, "label98");
  GLADE_HOOKUP_OBJECT (config_window, config_button_smoothing, "config_button_smoothing");
  GLADE_HOOKUP_OBJECT (config_window, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (config_window, config_combobox_displaymode, "config_combobox_displaymode");
  GLADE_HOOKUP_OBJECT (config_window, label99, "label99");
  GLADE_HOOKUP_OBJECT (config_window, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (config_window, config_combobox_lighting, "config_combobox_lighting");
  GLADE_HOOKUP_OBJECT (config_window, label100, "label100");
  GLADE_HOOKUP_OBJECT (config_window, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (config_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (config_window, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (config_window, config_spinbutton_mapwidth, "config_spinbutton_mapwidth");
  GLADE_HOOKUP_OBJECT (config_window, label101, "label101");
  GLADE_HOOKUP_OBJECT (config_window, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (config_window, config_spinbutton_mapheight, "config_spinbutton_mapheight");
  GLADE_HOOKUP_OBJECT (config_window, label103, "label103");
  GLADE_HOOKUP_OBJECT (config_window, label104, "label104");
  GLADE_HOOKUP_OBJECT (config_window, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (config_window, config_combobox_faceset, "config_combobox_faceset");
  GLADE_HOOKUP_OBJECT (config_window, label102, "label102");
  GLADE_HOOKUP_OBJECT (config_window, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (config_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (config_window, config_button_save, "config_button_save");
  GLADE_HOOKUP_OBJECT (config_window, config_button_apply, "config_button_apply");
  GLADE_HOOKUP_OBJECT (config_window, config_button_close, "config_button_close");

  return config_window;
}

GtkWidget*
create_about_window (void)
{
  GtkWidget *about_window;
  GtkWidget *about_vbox;
  GtkWidget *about_hbox_image;
  GtkWidget *scrolledwindow10;
  GtkWidget *about_textview;
  GtkWidget *about_close;

  about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (about_window, 500, 500);
  gtk_window_set_title (GTK_WINDOW (about_window), _("About Crossfire"));
  gtk_window_set_position (GTK_WINDOW (about_window), GTK_WIN_POS_CENTER_ON_PARENT);

  about_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (about_vbox);
  gtk_container_add (GTK_CONTAINER (about_window), about_vbox);

  about_hbox_image = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (about_hbox_image);
  gtk_box_pack_start (GTK_BOX (about_vbox), about_hbox_image, FALSE, TRUE, 0);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow10);
  gtk_box_pack_start (GTK_BOX (about_vbox), scrolledwindow10, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow10), GTK_SHADOW_IN);

  about_textview = gtk_text_view_new ();
  gtk_widget_show (about_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), about_textview);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (about_textview), FALSE);

  about_close = gtk_button_new_with_mnemonic (_("Close"));
  gtk_widget_show (about_close);
  gtk_box_pack_start (GTK_BOX (about_vbox), about_close, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (about_close, GTK_CAN_FOCUS);

  g_signal_connect ((gpointer) about_close, "clicked",
                    G_CALLBACK (on_about_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_window, about_window, "about_window");
  GLADE_HOOKUP_OBJECT (about_window, about_vbox, "about_vbox");
  GLADE_HOOKUP_OBJECT (about_window, about_hbox_image, "about_hbox_image");
  GLADE_HOOKUP_OBJECT (about_window, scrolledwindow10, "scrolledwindow10");
  GLADE_HOOKUP_OBJECT (about_window, about_textview, "about_textview");
  GLADE_HOOKUP_OBJECT (about_window, about_close, "about_close");

  return about_window;
}

