/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_root (void);
GtkWidget* create_metaserver_window (void);
GtkWidget* create_keybinding_window (void);
GtkWidget* create_spell_window (void);
GtkWidget* create_config_window (void);
GtkWidget* create_about_window (void);
