{
  "rules": [
  {
  "match" : ["violet"],
  "pre" : [["quest", "port_joseph/MooglyBill", "0-30"]],
  "post" : [["quest", "port_joseph/MooglyBill", "40"]],
  "msg" : ["Ah so Portia sent ye. . .'\nThe king's navy is attacking the fort!  This is as far as I dare take ye.\nThe grave is under the shadow of the wall to the north.  Return with the name of the island where he buried his treasure . . ."]
  }
]}
